services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: bun_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@bun_db:5432/postgres
    command: >
      sh -c "
        bun run db:migrate
        bun run --hot src/index.ts
      "
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: bun_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  default:
    driver: bridge