services:

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: debug
    container_name: bun_migrate
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@bun_db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: bun_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.prod
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@bun_db:5432/postgres
    depends_on:
      migrate:
        condition: service_completed_successfully

  db:
    image: postgres:15
    container_name: bun_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: